<script>
    import Modal from "../components/Modal.svelte";
    import Layout from "../components/Layout.svelte";
    import { currentlyActive } from '../stores.js';
    import SpeakerItem from "../components/SpeakerItem.svelte";
    currentlyActive.set("speakers");
</script>

<Layout>
    <Modal title="SPEAKERS">
        <div id="content">
            <SpeakerItem speakerName="Jeff Rothschild" image="https://s3.us-west-2.amazonaws.com/secure.notion-static.com/4c65dd35-ec2f-4cde-b41e-3444a8095cd3/jeff-rothschild.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210928%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210928T210928Z&X-Amz-Expires=86400&X-Amz-Signature=baeddfec53e57eb62b180c0c3e37193ba23e48695822c1729794dbdae998c7aa&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22jeff-rothschild.jpg%22" eventName="Jeff Rothschild — Entrepreneur and Investor" eventDesc="Jeff Rothschild and was co-founder of the storage software company Veritas Software and the online gaming company Mpath Interactive. Jeff joined Facebook in 2005 as VP Infrastructure Enginereering and spent 10 years  focused on scalability, availability, and performance.<br />Since leaving Facebook in 2015, Jeff has been working as an investor and mentor to entrepreneurs and is on the board of Pure Storage. Jeff also serves as Vice-Chair of the Board of Trust of Vanderbilt University, where he had earned his BA in Psychology and MS in Computer Science. Jeff’s philanthropic and impact investing activities include educational projects supporting disadvantaged students, a shoe company in Guatemala, an ophthalmologic hospital providing restorative eye surgery in western Kenya, and farmers cooperatives and credit unions, also in Kenya." />
            <SpeakerItem speakerName="Anuradha Bajpai" image="https://s3.us-west-2.amazonaws.com/secure.notion-static.com/6264fe62-a14c-4dec-a592-5e2cd3fdb834/Anuradha_photo.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210928%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210928T211504Z&X-Amz-Expires=86400&X-Amz-Signature=9721c160c12c29f57c6ee4b36a5cb0e4cd9327577a7e71e5bbec3641d3243c98&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Anuradha%2520photo.jpg%22" eventName="Anuradha Bajpai — Strategic Cloud Engineer at Google" eventDesc="Anuradha has 17 years of experience architecting, designing and implementing cloud based scalable applications.<br />Currently she is working with Google as Strategic Cloud Engineer. In the last 2 years since joining Google, she has received more than 15 awards in addition to a prestigious Google Stratosphere Award for her outstanding work and contributions at Google Cloud. At Google Cloud Professional services, Anuradha provides technical leadership on architecting and migrating business critical applications for major enterprise customers<br />Anuradha has significant experience in global delivery and leading Software Engineers for multiple projects In her previous role as product owner architect at Siemens, she led the first delivery of the MindSphere Integrated Lake product. She has also co-founded a social networking startup that selected in an Accelerator Program at one of the tech hubs in Google Entrepreneurs network and secured an offer for further investment. She led start-up from idea to launch and scaled for users from more than 60 countries." />
            <SpeakerItem speakerName="Kevin B Johnson" image="https://s3.us-west-2.amazonaws.com/secure.notion-static.com/2cb78afb-10bd-4d25-814a-8fd143d46029/Jan_10_2019_11_45_AM_2019-01-15_16-56-55.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210928%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210928T211516Z&X-Amz-Expires=86400&X-Amz-Signature=1adb3cf960ce11d57c7d7ecdcbbed6fec925cf06caeb7ea5b8d8c1e55a54a933&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Jan%252010%252C%25202019%252011_45%2520AM_2019-01-15_16-56-55.jpeg%22" eventName="Kevin B Johnson — Pediatrician and Informatician at Vanderbilt University School of Medicine" eventDesc="Kevin B. Johnson, MD, MS, FAAP, FACMI, FAMIA, FIAHSI is a Professor and Chair of Biomedical Informatics, with a joint appointment in the Department of Pediatrics at Vanderbilt University Medical Center. He received his MD from Johns Hopkins Hospital in Baltimore and his MS in Medical Informatics from Stanford University. In 1992 he returned to Johns Hopkins where he served as a Pediatric Chief Resident. He was a member of the faculty in both Pediatrics and Biomedical Information Sciences at Johns Hopkins until 2002, when he was recruited to Vanderbilt University. He also is a board-certified Pediatrician.<br \> Dr. Johnson is an internationally respected developer and evaluator of clinical technology. His research interests have been related to developing and encouraging adoption of clinical information systems to improve patient safety and compliance with practice guidelines. He is widely known for his work with e-prescribing and computer documentation, as well as his recent creative endeavors to communicate science to audiences, including a feature length documentary about health information exchange.<br \> He is the author of over 150 publications and has won dozens of awards over his Notably, he was elected to the American College of Medical Informatics in 2004, The Pediatric Society in 2010, the National Academy of Medicine (Institute of Medicine) in and the International Association of Health Science Informatics in 2021." />
        </div>
    </Modal>
</Layout>

<style>
    #content {
        overflow-y: auto;
        height: 50vh;
        padding-left: 5vw;
    }
</style>